Header
davudyuck/project-11 pull request #5
Opened 2022-12-01 23:41 UTC by MarinaMostova

2022-12-02 00:12 UTC, davudyuck commented on src/partials/header.html
> +              <use href="./src/images/icon.svg#phone"></use>
Не правильний шлях до файлу (./images...)

2022-12-02 00:13 UTC, davudyuck commented on src/partials/header.html
> +              <use href="../images/icon.svg#facebook"></use>
Зайва крапка (./images...)

2022-12-02 00:13 UTC, davudyuck commented on src/partials/header.html
> +              <use href="../images/icon.svg#telegram"></use>
Зайва крапка (./images...)

2022-12-02 00:46 UTC, davudyuck commented on src/partials/header.html
> +            <span class="navigation__phone">067 275 85 40</span>
Другий номер необхідно зробити не спаном, а посиланням та винести під перший номер
<a>Готель</a>
<a>Іконка перший номер</a>
<a>Другий номер</a>

2022-12-02 00:53 UTC, davudyuck requested changes
Перевірив тільки HTML

2022-12-02 11:45 UTC, MarinaMostova commented on src/partials/header.html
> +              <use href="./src/images/icon.svg#phone"></use>
Шлях виправлено

2022-12-02 15:50 UTC, MarinaMostova commented on src/partials/header.html
> +              <use href="../images/icon.svg#facebook"></use>
відредаговано

2022-12-02 15:51 UTC, MarinaMostova commented on src/partials/header.html
> +              <use href="../images/icon.svg#telegram"></use>
відредаговано

2022-12-02 15:51 UTC, MarinaMostova commented on src/partials/header.html
> +            <span class="navigation__phone">067 275 85 40</span>
відредаговано

2022-12-04 13:42 UTC, davudyuck approved these changes

2022-12-04 13:42 UTC, merged